/* AUTO-GENERATED by tools/gen_font.py -- do not edit by hand.
 * Single-stroke vector font, Flash-resident.  Source: tools/vectorfont.py
 */
#pragma once
#include <stdint.h>

#define FONT_FP          16      /* points are in 1/FONT_FP font units */
#define FONT_FIRST       32
#define FONT_LAST        127
#define FONT_CAP_HEIGHT  24

typedef struct { int16_t x, y; } fpt_t;
typedef struct { uint16_t first; uint8_t n; } fstroke_t;
typedef struct { uint8_t advance; uint16_t first_stroke; uint8_t n_stroke; } glyph_t;

extern const fpt_t     font_pts[564];
extern const fstroke_t font_strokes[109];
extern const glyph_t   font_glyphs[96];   /* index = ascii - FONT_FIRST */
