"""
Emit firmware/stm32/src/font_vec.{c,h} from vectorfont.GLYPHS.

The C table is a flat, Flash-resident encoding:
  font_pts[]     : all polyline points, int16 fixed-point (x16 font units)
  font_strokes[] : {first_pt, n_pt} per stroke
  font_glyphs[]  : indexed by ASCII 32..127 -> {advance, first_stroke, n_stroke}

Run this whenever vectorfont.py changes:
  python gen_font.py
"""

import os
from vectorfont import GLYPHS, CAP_HEIGHT

FP = 16                       # fixed-point scale (1/16 font unit)
FIRST, LAST = 32, 127
HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "firmware", "stm32", "src")


def build():
    pts = []
    strokes = []
    glyphs = []
    for code in range(FIRST, LAST + 1):
        g = GLYPHS.get(chr(code), GLYPHS[" "])
        first_stroke = len(strokes)
        for stroke in g.strokes:
            first_pt = len(pts)
            for (x, y) in stroke:
                pts.append((int(round(x * FP)), int(round(y * FP))))
            strokes.append((first_pt, len(stroke)))
        glyphs.append((int(round(g.advance)), first_stroke, len(g.strokes)))
    return pts, strokes, glyphs


def emit():
    pts, strokes, glyphs = build()
    hdr = f"""/* AUTO-GENERATED by tools/gen_font.py -- do not edit by hand.
 * Single-stroke vector font, Flash-resident.  Source: tools/vectorfont.py
 */
#pragma once
#include <stdint.h>

#define FONT_FP          {FP}      /* points are in 1/FONT_FP font units */
#define FONT_FIRST       {FIRST}
#define FONT_LAST        {LAST}
#define FONT_CAP_HEIGHT  {int(CAP_HEIGHT)}

typedef struct {{ int16_t x, y; }} fpt_t;
typedef struct {{ uint16_t first; uint8_t n; }} fstroke_t;
typedef struct {{ uint8_t advance; uint16_t first_stroke; uint8_t n_stroke; }} glyph_t;

extern const fpt_t     font_pts[{len(pts)}];
extern const fstroke_t font_strokes[{len(strokes)}];
extern const glyph_t   font_glyphs[{len(glyphs)}];   /* index = ascii - FONT_FIRST */
"""

    def pts_c():
        rows = []
        for i in range(0, len(pts), 6):
            chunk = pts[i:i + 6]
            rows.append("  " + " ".join(f"{{{x},{y}}}," for (x, y) in chunk))
        return "\n".join(rows)

    def strokes_c():
        rows = []
        for i in range(0, len(strokes), 6):
            chunk = strokes[i:i + 6]
            rows.append("  " + " ".join(f"{{{a},{b}}}," for (a, b) in chunk))
        return "\n".join(rows)

    def glyphs_c():
        rows = []
        for i, (adv, fs, ns) in enumerate(glyphs):
            ch = chr(FIRST + i)
            disp = ch if ch.isprintable() and ch != "\\" else "?"
            rows.append(f"  {{{adv:>3},{fs:>4},{ns:>2}}},  /* '{disp}' */")
        return "\n".join(rows)

    src = f"""/* AUTO-GENERATED by tools/gen_font.py -- do not edit by hand. */
#include "font_vec.h"

const fpt_t font_pts[{len(pts)}] = {{
{pts_c()}
}};

const fstroke_t font_strokes[{len(strokes)}] = {{
{strokes_c()}
}};

const glyph_t font_glyphs[{len(glyphs)}] = {{
{glyphs_c()}
}};
"""
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "font_vec.h"), "w") as f:
        f.write(hdr)
    with open(os.path.join(OUT, "font_vec.c"), "w") as f:
        f.write(src)
    print(f"font_vec: {len(pts)} pts, {len(strokes)} strokes, "
          f"{len(glyphs)} glyphs -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    emit()
